### ISSUE TITLE
[Request] Options to change Uber meter and percentage and Engie's metal count

### ISSUE THREAD

**Issue by Delfite** [p3tr1ch0r/leadhud#3]
Add an option to switch between different Uber meter styles as well as if the Uber percentage should be beneath the crosshair like how Engineer's metal count is by default. Oh yeah, Engie's metal count should have the same thing as Uber percentage, just to keep things fair of course lol

**Comment by leadscales** [comment]
Uber charge customization has been implemented and will be pushed soon, and metal count customization is in the works. I'll update you on it here.

**Comment by leadscales** [comment]
commit b2f1880e2b7847eb2dda57bd49071a28158b3818 has added what I believe you requested. Closed.
